name: AWOTER
version: 1

libraries:
- name: flask
  version: "0.10.1"

- name: Flask-Bootstrap
  version: "3.0.3.1"

- name: Flask-Login
  version: "0.3.1"

- name: Flask-Mail
  version: "0.9.0"

- name: Flask-Migrate
  version: "1.1.0"

- name: Flask-Moment
  version: "0.2.1"

- name: Flask-PageDown
  version: "0.1.4"

- name: Flask-SQLAlchemy
  version: "1.0"

- name: Flask-Script
  version: "0.6.6"

- name: Flask-WTF
  version: "0.9.4"

- name: Jinja2
  version: "2.7.1"

- name: Mako
  version: "0.9.1"

- name: Markdown
  version: "2.3.1"

- name: MarkupSafe
  version: "0.18"

- name: SQLAlchemy
  version: "0.9.9"

- name: WTForms
  version: "1.0.5"

- name: Werkzeug
  version: "0.10.4"

- name: alembic
  version: "0.6.2"

- name: bleach
  version: "1.4.0"

- name: blinker
  version: "1.3"

- name: html5lib
  version: "1.0b3"

- name: itsdangerous
  version: "0.23"

- name: six
  version: "1.4.1"

handlers:
- url: /static
  static_dir: /app/static
