"""empty message

Revision ID: 32785e3a323f
Revises: None
Create Date: 2016-03-01 09:59:02.426000

"""

# revision identifiers, used by Alembic.
revision = '32785e3a323f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    op.drop_column('users', 'default')
    op.drop_column('users', 'permission')
    op.drop_index('ix_users_default', 'users')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_default', 'users', ['default'], unique=False)
    op.add_column('users', sa.Column('permission', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('default', sa.BOOLEAN(), nullable=True))
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
