"""empty message

Revision ID: 45f54d558681
Revises: None
Create Date: 2016-02-27 00:25:03.333000

"""

# revision identifiers, used by Alembic.
revision = '45f54d558681'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
