"""empty message

Revision ID: d3b5c724c1d
Revises: None
Create Date: 2016-03-01 17:55:22.214000

"""

# revision identifiers, used by Alembic.
revision = 'd3b5c724c1d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
